language: node_js
node_js:
  - "8"
services:
  - docker

install:
  - cd spec/integration
  - docker-compose build

script:
  - docker-compose up --abort-on-container-exit

after_script:
  - docker-compose rm -f