language: node_js
node_js:
  - "8"
services:
  - docker

install:
  - cd integration_tester
  - docker-compose build

script:
  - docker-compose run eventer-unit-test-image
  - docker-compose run integration-tester

after_script:
  - docker-compose down

notifications:
  email: false