language: node_js
node_js:
  - "8"
services:
  - docker

install:
  - cd integration_tester
  - docker-compose build

script:
  - docker-compose run eventer-unit-test-image
  - docker-compose run integration-tester

after_script:
  - docker-compose down

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker-compose push eventer;
    fi

notifications:
  email: false