language: node_js
node_js:
  - "8"
services:
  - docker

install:
  - docker build -t disappearer/eventer .
  - docker run -d -p 127.0.0.1:80:80 --name eventer disappearer/eventer

script:
  - docker ps | grep eventer