language: node_js
node_js:
  - "8"
services:
  - docker

install:
  - cd spec/integration
  - docker-compose build

script:
  - docker-compose up --exit-code-from integration-tester

after_script:
  - docker-compose rm -f