version: '3'

services:
  integration-tester:
    build: .
    links:
      - eventer
      - db-eventer
    environment:
      - EVENTER_URL=http://eventer:3000
      - DB_URL=mongodb://db-eventer/eventer_integration_test
  
  eventer:
    environment:
      - NODE_ENV=integration-test
      - DB_URL=mongodb://db-eventer/eventer_integration_test
      - DB=mongo
      - GOOGLE_CLIENT_ID=x
      - GOOGLE_CLIENT_SECRET=x
      - DEBUG=eventer:log eventer:debug
    build: ../..
    command: npm start
    links:
      - db-eventer
    expose:
      - "3000"

  eventer-unit-test-image:
    environment:
      - NODE_ENV=unit-test
      - DB_URL=mongodb://db-eventer/eventer_unit_test
      - DB=mongo
      - GOOGLE_CLIENT_ID=x
      - GOOGLE_CLIENT_SECRET=x
      - DEBUG=eventer:log eventer:debug
    build: ../..
    command: npm test
    links:
      - db-eventer

  db-eventer:
    image: mongo:jessie
    expose:
      - "27017"